# Generated by Django 4.2.2 on 2023-08-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=250),
            preserve_default=False,
        ),
    ]
